//
//  TopRatedInteractor.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class TopRatedInteractor {
}

// MARK: - Extensions -

extension TopRatedInteractor: TopRatedInteractorInterface {
}
