//
//  TopRatedViewController.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class TopRatedViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: TopRatedPresenterInterface!

    // MARK: - Private properties -

    private let tableView = UITableView()

    private let disposeBag = DisposeBag()

    private lazy var tableDataSource: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: tableView)
    }()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        setupView()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
}

// MARK: - Extensions -

extension TopRatedViewController: TopRatedViewInterface {
}

private extension TopRatedViewController {

    func setupView() {
        guard let rightBarButton = navigationItem.rightBarButtonItem else { return }
        let output = TopRated.ViewOutput(
            settings: rightBarButton.rx.tap.asSignal()
        )

        let input = presenter.configure(with: output)
        handle(shows: input.shows)
    }

    func handle(shows: Driver<[TableCellItem]>) {
        shows
            .drive(tableDataSource.rx.items)
            .disposed(by: disposeBag)
    }
}

private extension TopRatedViewController {

    func setupUI() {
        addSubviews()
        configureView()
        configureSubviews()
        defineConstraints()
    }

    func addSubviews() {
        view.addSubview(tableView)
    }

    func configureView() {
        title = "Top Rated"
        navigationController?.styleNavBar(prefersLargeTitles: true)
        navigationItem.rightBarButtonItem = UIBarButtonItem(
            image: UIImage.TVShows.Icons.settings.withRenderingMode(.alwaysOriginal),
            style: .plain,
            target: nil,
            action: nil
        )

        view.backgroundColor = UIColor.TVShows.appWhite
    }

    func configureSubviews() {
        tableView.backgroundColor = UIColor.TVShows.appGrey
        tableView.registerClass(cellOfType: ShowTableViewCell.self)
    }

    func defineConstraints() {
        tableView.contentInsetAdjustmentBehavior = .always
        tableView.snp.makeConstraints {
            $0.edges.equalToSuperview()
        }
    }
}
