//
//  TopRatedPresenter.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class TopRatedPresenter {

    // MARK: - Private properties -

    private unowned let view: TopRatedViewInterface
    private let interactor: TopRatedInteractorInterface
    private let wireframe: TopRatedWireframeInterface
    private let disposeBag: DisposeBag

    // MARK: - Lifecycle -

    init(
        view: TopRatedViewInterface,
        interactor: TopRatedInteractorInterface,
        wireframe: TopRatedWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.disposeBag = DisposeBag()
    }
}

// MARK: - Extensions -

extension TopRatedPresenter: TopRatedPresenterInterface {

    func configure(with output: TopRated.ViewOutput) -> TopRated.ViewInput {
        onSettingsTapped(output.settings)
        let shows = fetchShows()
        let items = shows
            .map { [unowned self] in createItems(from: $0)}

        return TopRated.ViewInput(
            shows: items.map { $0 as [TableCellItem] }
        )
    }

    func onSettingsTapped(_ settings: Signal<Void>) {
        settings
            .emit(onNext: { [unowned self] _ in
                wireframe.goToSettings()
            })
            .disposed(by: disposeBag)
    }

    func fetchShows() -> Driver<[Show]> {
        return interactor
            .fetchShows()
            .handleLoadingAndError(with: view)
            .asDriver(onErrorJustReturn: [])
    }

    func createItems(from shows: [Show]) -> [ShowTableCellItem] {
        return shows.map {
            return ShowTableCellItem(
                show: $0,
                didSelect: { [unowned self] in wireframe.goToShowDetails(with: $0.show) })
        }
    }
}



