//
//  TopRatedPresenter.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class TopRatedPresenter {

    // MARK: - Private properties -

    private unowned let view: TopRatedViewInterface
    private let interactor: TopRatedInteractorInterface
    private let wireframe: TopRatedWireframeInterface
    private let disposeBag: DisposeBag

    // MARK: - Lifecycle -

    init(
        view: TopRatedViewInterface,
        interactor: TopRatedInteractorInterface,
        wireframe: TopRatedWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.disposeBag = DisposeBag()
    }
}

// MARK: - Extensions -

extension TopRatedPresenter: TopRatedPresenterInterface {

    func configure(with output: TopRated.ViewOutput) -> TopRated.ViewInput {
        handle(settings: output.settings)
        return TopRated.ViewInput()
    }

    func handle(settings: Signal<Void>) {
        settings
            .emit(onNext: { [unowned self] _ in
                wireframe.goToSettings()
            })
            .disposed(by: disposeBag)
    }

}
