//
//  TopRatedWireframe.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class TopRatedWireframe: BaseWireframe<TopRatedViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = TopRatedViewController()
        super.init(viewController: moduleViewController)

        let interactor = TopRatedInteractor()
        let presenter = TopRatedPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TopRatedWireframe: TopRatedWireframeInterface {

    func goToShowDetails(with id: String) {
        navigationController?.pushWireframe(ShowDetailsWireframe(with: id))
    }

    func goToSettings() {
        navigationController?.present(
            UINavigationController(rootViewController: SettingsWireframe().viewController),
            animated: true,
            completion: nil
        )
    }
}
