//
//  TopRatedInteractor.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class TopRatedInteractor {

    private let service: APIService
    private let sessionManager: SessionManager

    init(
        service: APIService = APIService.instance,
        sessionManager: SessionManager = .default
    ) {
        self.service = service
        self.sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension TopRatedInteractor: TopRatedInteractorInterface {

    func fetchShows() -> Single<[Show]> {
        service.rx
            .request(
                TopRatedResponse.self,
                router: ShowsRouter.topRatedShows,
                session: sessionManager.session
            )
            .map { $0.shows }
    }
}
