//
//  ReviewInterfaces.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 30.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ReviewWireframeInterface: WireframeInterface {
    func dismiss()
}

protocol ReviewViewInterface: ViewInterface, Progressable {
}

protocol ReviewPresenterInterface: PresenterInterface {
    func configure(with output: SendReview.ViewOutput) -> SendReview.ViewInput
}

protocol ReviewInteractorInterface: InteractorInterface {
    func submitReview(with rating: Int, comment: String?) -> Single<Void>
}

enum SendReview {

    struct ViewOutput {
        let close: Signal<Void>
        let rating: Driver<Int?>
        let comment: Driver<String?>
        let submit: Signal<Void>
    }

    struct ViewInput {
        let isSubmitEnabled: Driver<Bool>
    }

}
