//
//  ReviewInteractor.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 30.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ReviewInteractor {

    private let identifier: String
    private let service: APIService
    private let sessionManager: SessionManager

    init(
        identifier: String,
        service: APIService = APIService.instance,
        sessionManager: SessionManager = .default
    ) {
        self.identifier = identifier
        self.service = service
        self.sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension ReviewInteractor: ReviewInteractorInterface {

    func submitReview(with rating: Int, comment: String?) -> Single<Void> {
        let params: [String : Any] = [
            "rating": rating,
            "comment": comment ?? "",
            "show_id": identifier
        ]

        return service.rx
            .requestResponse(
                router: ReviewRouter.submitReview(with: params),
                session: sessionManager.session
            )
            .map { _ in () }
    }
}
