//
//  SettingsWireframe.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SettingsWireframe: BaseWireframe<SettingsViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = SettingsViewController()
        super.init(viewController: moduleViewController)

        let interactor = SettingsInteractor()
        let presenter = SettingsPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SettingsWireframe: SettingsWireframeInterface {
    func dismiss() {
        navigationController?.dismiss(animated: true, completion: nil)
    }

    func openGallery(delegate: SettingsPresenter) {
        let picker = UIImagePickerController()
        picker.sourceType = .photoLibrary
        picker.allowsEditing = true
        navigationController?.present(picker, animated: true, completion: nil)
    }

    func goToLogin() {
        navigationController?.dismiss(animated: true, completion: { () in
            NotificationCenter.default.post(.didLogout)
        })
    }
}
