//
//  SettingsInterfaces.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol SettingsWireframeInterface: WireframeInterface {
    func dismiss()
    func openGallery(delegate: SettingsPresenter)
    func goToLogin()
}

protocol SettingsViewInterface: ViewInterface, Progressable {
}

protocol SettingsPresenterInterface: PresenterInterface {
    func configure(with output: Settings.ViewOutput) -> Settings.ViewInput
}

protocol SettingsInteractorInterface: InteractorInterface {
    var user: Single<User> { get }
    func updateUser(with data: Data) -> Single<User>
    func deleteAuthInfo()
}

enum Settings {

    struct ViewOutput {
        let close: Signal<Void>
        let changePhoto: Signal<Void>
        let logout: Signal<Void>
    }

    struct ViewInput {
        let user: Driver<User>
    }

}
