//
//  ShowsInteractor.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ShowsInteractor {

    private let service: APIService
    private let sessionManager: SessionManager

    init(
        service: APIService = APIService.instance,
        sessionManager: SessionManager = .default
    ) {
        self.service = service
        self.sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension ShowsInteractor: ShowsInteractorInterface {

    func shows(with pagination: Pagination?) -> Single<ShowsResponse> {
        var params: [String: Int] = [:]
        if let lastPage = pagination {
            params = [
                "page": lastPage.page + 1,
                "items": lastPage.items
            ]
        }
        return service.rx
            .request(
                ShowsResponse.self,
                router: ShowsRouter.shows(with: params),
                session: sessionManager.session
            )
    }
}
