//
//  ShowsViewController.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 23.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ShowsViewController: UIViewController, Refreshable {

    // MARK: - Public properties -

    lazy var refreshControl: UIRefreshControl = {
        let refreshControl = UIRefreshControl()
        tableView.refreshControl = refreshControl
        return refreshControl
    }()

    var presenter: ShowsPresenterInterface!

    // MARK: - Private properties -

    private let tableView = UITableView()

    private let disposeBag = DisposeBag()

    private lazy var tableDataSource: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: tableView)
    }()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        setupView()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
}

// MARK: - Extensions -

extension ShowsViewController: ShowsViewInterface {
}

private extension ShowsViewController {

    func setupView() {
        guard let rightBarButton = navigationItem.rightBarButtonItem else { return }
        let pullToRefresh = refreshControl.rx
            .controlEvent(.valueChanged)
            .asDriver()
            .map { _ in }

        let willDisplayLastCell = tableView.rx
            .reachedBottomOnceWith(restart: pullToRefresh)

        let output = Shows.ViewOutput(
            settings: rightBarButton.rx.tap.asSignal(),
            pullToRefresh: pullToRefresh,
            willDisplayLastCell: willDisplayLastCell
        )
        let input = presenter.configure(with: output)

        handle(shows: input.shows)
    }

    func handle(shows: Driver<[TableCellItem]>) {
        shows
            .do(onNext: { [unowned self] _ in self.endRefreshing() })
            .drive(tableDataSource.rx.items)
            .disposed(by: disposeBag)
    }
}

private extension ShowsViewController {

    func setupUI() {
        addSubviews()
        configureView()
        configureSubviews()
        defineConstraints()
    }

    func addSubviews() {
        view.addSubview(tableView)
    }

    func configureView() {
        title = "Shows"
        navigationController?.styleNavBar(prefersLargeTitles: true)
        navigationItem.rightBarButtonItem = UIBarButtonItem(
            image: UIImage.TVShows.Icons.settings.withRenderingMode(.alwaysOriginal),
            style: .plain,
            target: nil,
            action: nil
        )

        view.backgroundColor = UIColor.TVShows.appWhite
    }

    func configureSubviews() {
        tableView.backgroundColor = UIColor.TVShows.appGrey
        tableView.registerClass(cellOfType: ShowTableViewCell.self)
    }

    func defineConstraints() {
        tableView.snp.makeConstraints {
            $0.edges.equalTo(view.safeAreaLayoutGuide)
        }
    }
}
