//
//  ShowDetailsInterfaces.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 24.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol ShowDetailsWireframeInterface: WireframeInterface {
}

protocol ShowDetailsViewInterface: ViewInterface, Progressable {
}

protocol ShowDetailsPresenterInterface: PresenterInterface {
    func configure(with output: ShowDetails.ViewOutput) -> ShowDetails.ViewInput
}

protocol ShowDetailsInteractorInterface: InteractorInterface {
    func fetchShow() -> Single<Show>
    func fetchReviews() -> Single<[Review]>
}

enum ShowDetails {

    struct ViewOutput {
        let createReview: Signal<Void>
    }

    struct ViewInput {
        let show: Driver<Show>
        let reviews: Driver<[TableCellItem]>
    }

}
