//
//  ShowDetailsInteractor.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 24.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class ShowDetailsInteractor {
}

// MARK: - Extensions -

extension ShowDetailsInteractor: ShowDetailsInteractorInterface {
}
