//
//  ShowDetailsPresenter.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 24.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class ShowDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: ShowDetailsViewInterface
    private let interactor: ShowDetailsInteractorInterface
    private let wireframe: ShowDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: ShowDetailsViewInterface,
        interactor: ShowDetailsInteractorInterface,
        wireframe: ShowDetailsWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ShowDetailsPresenter: ShowDetailsPresenterInterface {

    func configure(with output: ShowDetails.ViewOutput) -> ShowDetails.ViewInput {
        return ShowDetails.ViewInput()
    }

}
