import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIColor {
	enum TVShows {}
}

extension UIColor.TVShows {

	static var appWhite: UIColor { return UIColor(named: "appWhite", in: .main, compatibleWith: nil)! }
	static var appPurple: UIColor { return UIColor(named: "appPurple", in: .main, compatibleWith: nil)! }
	static var accentColor: UIColor { return UIColor(named: "AccentColor", in: .main, compatibleWith: nil)! }
}
