import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIImage {
	enum TVShows {}
}

extension UIImage.TVShows {

	enum Icons {
		static var icVisible: UIImage { return UIImage(named: "Icons/ic-visible", in: .main, compatibleWith: nil)! }
		static var icCheckboxSelected: UIImage { return UIImage(named: "Icons/ic-checkbox-selected", in: .main, compatibleWith: nil)! }
		static var icCheckboxUnselected: UIImage { return UIImage(named: "Icons/ic-checkbox-unselected", in: .main, compatibleWith: nil)! }
		static var icInvisible: UIImage { return UIImage(named: "Icons/ic-invisible", in: .main, compatibleWith: nil)! }
        static var shows: UIImage { return UIImage(named: "Icons/shows", in: .main, compatibleWith: nil)! }
        static var topRated: UIImage { return UIImage(named: "Icons/topRated", in: .main, compatibleWith: nil)! }
        static var settings: UIImage { return UIImage(named: "Icons/settings", in: .main, compatibleWith: nil)! }
        static var showPlaceholder: UIImage { return UIImage(named: "Icons/ic-show-placeholder", in: .main, compatibleWith: nil)! }
        static var profilePlaceholder: UIImage { return UIImage(named: "Icons/ic-profile-placeholder", in: .main, compatibleWith: nil)! }
        static var starSelected: UIImage { return UIImage(named: "Icons/ic-star-selected", in: .main, compatibleWith: nil)! }
        static var starDeselected: UIImage { return UIImage(named: "Icons/ic-star-deselected", in: .main, compatibleWith: nil)! }
	}

	static var loginBackground: UIImage { return UIImage(named: "loginBackground", in: .main, compatibleWith: nil)! }
	static var logo: UIImage { return UIImage(named: "logo", in: .main, compatibleWith: nil)! }
}
