//
//  HomeInterfaces.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 16.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
}

enum Home {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
