//
//  HomeWireframe.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 16.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HomeWireframe: BaseWireframe<HomeTabBarController> {

    // MARK: - Module setup -

    init() {
        let topRatedNav = UINavigationController(rootViewController: TopRatedWireframe().viewController)
        let showsNav = UINavigationController(rootViewController: ShowsWireframe().viewController)

        let moduleTabBarController = HomeTabBarController(viewControllers: [showsNav, topRatedNav])
        super.init(viewController: moduleTabBarController)
    }
}
