//
//  HomeWireframe.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 25.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HomeWireframe: BaseWireframe<HomeTabBarController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let topRatedNav = UINavigationController(rootViewController: TopRatedWireframe().viewController)
        let showsNav = UINavigationController(rootViewController: ShowsWireframe().viewController)

        let moduleTabBarController = HomeTabBarController(viewControllers: [showsNav, topRatedNav])
        super.init(viewController: moduleTabBarController)

        let interactor = HomeInteractor()
        let presenter = HomePresenter(interactor: interactor, wireframe: self)
        moduleTabBarController.presenter = presenter
    }
}

// MARK: - Extensions -

extension HomeWireframe: HomeWireframeInterface {

    func goToLogin() {
        navigationController?.setRootWireframe(LoginWireframe())
    }
}
