//
//  HomePresenter.swift
//  iOS-TvShows
//
//  Created by Filip Ban on 25.11.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class HomePresenter {

    // MARK: - Private properties -

    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface

    // MARK: - Lifecycle -

    init(
        interactor: HomeInteractorInterface,
        wireframe: HomeWireframeInterface
    ) {

        self.interactor = interactor
        self.wireframe = wireframe
        registerNotifications()
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
}

extension HomePresenter {

    func registerNotifications() {
        NotificationCenter
            .default
            .addObserver(
                forName: Notification.didLogout.name,
                object: nil,
                queue: nil
            ) { [weak self] _ in
                guard let self = self else { return }
                self.wireframe.goToLogin()
            }
    }
}
