# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iOS-TvShows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-TvShows
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'KeychainAccess'
  pod 'SnapKit'
end
